---

- name: Install MariaDB
  ansible.builtin.package:
    name: mariadb-server
    state: present

- name: Install MySQL-python
  apt:
    name: python3-mysqldb
    state: present

- name: Create slurm db
  mysql_db:
    name: "{{ slurm_db_name }}"
    state: present

- name: Create slurm user
  mysql_user:
    name: "{{ slurm_db_username }}"
    password: "{{ slurm_db_pass }}"
    priv: '*.*:ALL'
    state: present
