---

- name: Install Slurm DB packages
  ansible.builtin.package:
    name: "{{ __slurm_packages.slurmdbd }}"
    state: "{{ 'latest' if slurm_upgrade else 'present' }}"

- name: Create slurm log directory
  ansible.builtin.file:
    path: "{{ __slurmdbd_config_merged.LogFile | dirname }}"
    owner: "{{ __slurm_user_name }}"
    group: "{{ __slurm_group_name }}"
    mode: 0755
    state: directory
  when: slurm_create_dirs and __slurmdbd_config_merged.LogFile != omit

- name: Include config dir creation tasks
  ansible.builtin.include_tasks: _inc_create_config_dir.yml
  when: slurm_create_dirs

- name: Create slurmdbd systemd drop-in directory
  ansible.builtin.file:
    path: "/etc/systemd/system/slurmdbd.service.d"
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
    state: directory

- name: Install slurmdbd systemd drop-in
  ansible.builtin.template:
    src: 10-slurmdbd_overrides.conf
    dest: "/etc/systemd/system/slurmdbd.service.d/10-slurmdbd_overrides.conf"
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"

- name: Reload systemd configurations
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Install slurmdbd.conf
  ansible.builtin.template:
    src: generic.conf.j2
    dest: "{{ slurm_config_dir }}/{{ item.name }}"
    owner: "{{ __slurm_user_name }}"
    group: root
    mode: 0600
  with_items:
    - name: slurmdbd.conf
      config: __slurmdbd_config_merged
  loop_control:
    label: "{{ item.name }}"
  notify:
    - Reload slurmdbd
